engines:
  # https://docs.codeclimate.com/docs/eslint
  # ES Linting requires an .eslintrc file to tweak checks.
  eslint:
    enabled: false
  markdownlint:
    enabled: true
  # We shouldn't actually have css in this repo.
  csslint:
    enabled: false
  # We don't lint our coffee. Eew.
  coffeelint:
    enabled: false
  # SCSS Lint requires a .scss-lint.yml file in the repo in order to tweak settings.
  # Withouth the .scss-lint.yml file it will run with the defaults.
  # Defaults file: https://github.com/brigade/scss-lint/blob/master/config/default.yml
  scss-lint:
    enabled: true
    checks:
      ColorVariable:
        enabled: false
      PropertySortOrder:
        enabled: false
      LeadingZero:
        enabled: false
      StringQuotes:
        enabled: false
  phpcodesniffer:
    enabled: false
  phpmd:
    enabled: false
  # https://docs.codeclimate.com/docs/phan
  phan:
    enabled: false
  # https://docs.codeclimate.com/docs/duplication
  duplication:
    enabled: true
    # exclude_paths:
    #   - examples/
    config:
      languages:
        javascript:
          mass_threshold: 50
          # count_threshold: 3
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
      - todo
ratings:
  paths:
  - "**.css"
  - "**.scss"
  - "**.sass"
  - "**.js"
  - "**.md"
# exclude these files/paths
exclude_paths:
- "test"
- "tests"
- "vendor"
- "vendors"
- "node_modules"
