version: "2"
checks:
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 40
plugins:
  # https://docs.codeclimate.com/docs/eslint
  # ES Linting requires an .eslintrc file to tweak checks.
  eslint:
    enabled: true
  markdownlint:
    enabled: false
    checks:
      MD029:
        enabled: false
      # Disable inline html check because homepage.md needs it.
      MD033:
        enabled: false
  # We shouldn't actually have css in this repo.
  csslint:
    enabled: false
  # We don't lint our coffee. Eew.
  coffeelint:
    enabled: false
  # SASS Lint requires a .sass-lint.yml file in the repo in order to tweak settings.
  # Withouth the .sass-lint.yml file it will run with the defaults.
  # Defaults file: https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml
  sass-lint:
    enabled: true
  # SCSS Lint requires a .scss-lint.yml file in the repo in order to tweak settings.
  # Withouth the .scss-lint.yml file it will run with the defaults.
  # Defaults file: https://github.com/brigade/scss-lint/blob/master/config/default.yml
  scss-lint:
    enabled: false
  phpcodesniffer:
    enabled: false
  phpmd:
    enabled: false
  # https://docs.codeclimate.com/docs/phan
  phan:
    enabled: false
  # https://docs.codeclimate.com/docs/duplication
  duplication:
    enabled: true
    # exclude_paths:
    #   - examples/
    config:
      languages:
        javascript:
          mass_threshold: 50
          # count_threshold: 3
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
      - todo
# exclude these files/paths
exclude_patterns:
- "test"
- "tests"
- "vendor"
- "vendors"
- "node_modules"
- "core/dist/**/*"
- "core/src/scss/core/_normalize.scss"
- "composer.json"
- "package.json"
- "webpack.config.js"
- "developer"
- "examples"
