# Documentation on the rules:
# https://github.com/sasstools/sass-lint/tree/master/docs/rules
#
files:
  ignore:
    - vendor/**/*.scss
    - node_modules/**/*.scss
    - kss/builder/decanter/**/*.scss
  include: "**/*.s+(a|c)ss"
rules:
  brace-style:
    - 1
    -
      style: stroustrup
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  empty-line-between-blocks: 1
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 1
  force-attribute-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 1
    -
      convention: hyphenatedlowercase
  hex-length: 0
  leading-zero:
    - 1
    - include: true
  mixins-before-declarations: 0
  name-format: 0
  nesting-depth:
    - 1
    -
      max-depth: 4
  no-color-literals: 0
  no-css-comments: 0
  no-empty-rulesets: 1
  no-ids: 1
  no-mergeable-selectors: 0
  no-misspelled-properties: 1
  no-vendor-prefixes: 0
  no-url-domains: 0
  no-warn: 0
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: 1
  one-declaration-per-line: 1
  placeholder-in-extend: 1
  property-sort-order: 0
  quotes: 0
  shorthand-values: 0
  single-line-per-selector: 1
  space-after-colon: 1
  space-after-comma: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 1
