# Documentation on the rules:
# https://github.com/sasstools/sass-lint/tree/master/docs/rules
#
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'vendor/**/*.scss'
    - 'node_modules/**/*.scss'
rules:
  # Class Name Format
  class-name-format:
    - 1
    -
      convention: 'hyphenatedbem'
  function-name-format:
    - 1
    -
      convention: 'snakecase'
  # Consistency Rules
  extends-before-mixins: 1
  extends-before-declarations: 1
  mixins-before-declarations: 1
  # Require an empty line between blocks
  empty-line-between-blocks: 1
  no-empty-rulesets: 1
  final-newline: 1
  no-ids: 1
  leading-zero: 1
  name-format: 0
  nesting-depth: 0
  placeholder-in-extend: 1
  property-sort-order: 0
  no-misspelled-properties: 1
  shorthand-values: 0
  one-declaration-per-line: 1
  single-line-per-selector: 1
  space-after-comma: 1
  force-pseudo-nesting: 0
  quotes: 0
  no-css-comments: 0
  no-vendor-prefixes: 0
  # Space surrounding colons
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  brace-style:
    - 1
    -
      style: 'stroustrup'
  space-between-parens: 1
  trailing-semicolon: 1
  no-mergeable-selectors: 0
  # Color
  no-color-literals: 0
  hex-length: 0
