services:
  # What to call the service hosting the site. Because there is only
  # one service, it is automatically set as the default service, which
  # does a few things
  #   1. Clones the git repository into the service container
  #   2. Exposes port 80 to the Tugboat HTTP proxy
  #   3. Routes requests to the preview URL to this service
  apache:

    # Use the available version of Apache by not specifying a version
    image: pookmish/tugboat-nvm:latest

    # A set of commands to run while building this service
    commands:

      # Commands that set up the basic preview infrastructure
      init:
        - chmod +x ${TUGBOAT_ROOT}/.tugboat/build.sh &&  ${TUGBOAT_ROOT}/.tugboat/build.sh

    # Collection of urls to compare visual results.
    # visualdiffs:
    #   - /
    #   - /news
    #   - /events
    #   - /people
    #   - /research
    #   - /about
