services:
  node:
    image: tugboatqa/node
    expose: 3000
    checkout: false
    commands:
      # Used in the base image as setup.
      init:
        - mkdir -p /etc/service/node
        - |
          nvm install 14.5.0
          nvm use
          npm install

      # Used in each of the preview builds.
      build:
        - |
          nvm use
          touch dev/src/test.css
          touch dev/src/test.js
          cp dev/src/sample.test.html dev/src/test.html
          npm run build:dev
        - echo "#!/bin/sh" > /etc/service/node/run
        - echo "npm run start" >> /etc/service/node/run
        - chmod +x /etc/service/node/run

    # Collection of urls to compare visual results.
    visualdiffs:
      - /
