services:
  node:
    image: tugboatqa/node
    expose: 3000
    checkout: false
    commands:
      # Used in the base image as setup.
      init:
        - |
          sudo apt-get install g++ build-essential
          git clone https://github.com/su-sws/decanter-web.git styleguide
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
          NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 11.14.0
          cd styleguide
          nvm use
          npm install

      # Used in each of the preview builds.
      build:
        - |
          NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd styleguide
          nvm use
          npm install "https://github.com/su-sws/decanter.git#${TUGBOAT_GITHUB_HEAD}"
          npm run export
        - mkdir -p /etc/service/node
        - echo "#!/bin/sh" > /etc/service/node/run
        - echo "npm run start --prefix ${TUGBOAT_ROOT}/styleguide" >> /etc/service/node/run
        - chmod +x /etc/service/node/run
    # Collection of urls to compare visual results.
    visualdiffs:
      - /
