
services:
  # What to call the service hosting the site. Because there is only
  # one service, it is automatically set as the default service, which
  # does a few things
  #   1. Clones the git repository into the service container
  #   2. Exposes port 80 to the Tugboat HTTP proxy
  #   3. Routes requests to the preview URL to this service
  apache:

    # Use the available version of Apache by not specifying a version
    image: pookmish/tugboat-nvm:latest

    # A set of commands to run while building this service
    commands:

      # Commands that set up the basic preview infrastructure
      init:
        - cp ~/.bashrc ~/.profile
        - cp ~/.bashrc ~/.bash_profile
        - cp ~/.bashrc ~/.zshrc
        - nvm install 10.15.1

      build:
        - nvm use
        - npm install
        - npm run build
        - npm run styleguide
        - rm -R node_modules
        - ln -snf "${TUGBOAT_ROOT}/styleguide" "${DOCROOT}"

    # Collection of urls to compare visual results.
    # visualdiffs:
    #   - /
    #   - /news
    #   - /events
    #   - /people
    #   - /research
    #   - /about
