services:
  apache:
    image: tugboatqa/httpd
    commands:
      # Used in the base image as setup.
      init:
        - git clone https://github.com/su-sws/decanter-web.git styleguide
        - ln -snf "${TUGBOAT_ROOT}/styleguide" "${DOCROOT}"
        - cd $TUGBOAT_ROOT/styleguide
        - |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
          NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 11.14.0
          nvm use
          npm i git+ssh://git@github.com:su-sws/decanter.git#$TUGBOAT_GITHUB_HEAD
          npm install
          npm run export

      # Used in each of the preview builds.
      build:
        - cd styleguide
        - |
          NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use
          npm i git+ssh://git@github.com:su-sws/decanter.git#$TUGBOAT_GITHUB_HEAD
          npm install
          npm run export
    # Collection of urls to compare visual results.
    visualdiffs:
      - /
