services:
  node:
    image: tugboatqa/node
    expose: 3000
    checkout: false
    commands:
      # Used in the base image as setup.
      init:
        - mkdir -p /etc/service/node
        - |
          sudo apt-get install g++ build-essential
          git clone https://github.com/su-sws/decanter-web.git styleguide
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
          NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install
          cd styleguide
          nvm use
          npm install

      # Used in each of the preview builds.
      build:
        - |
          NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd styleguide
          nvm install
          nvm use
          npm install "https://github.com/su-sws/decanter.git#${TUGBOAT_GITHUB_HEAD}" --save --force
          npm audit fix
          npm run export
        - echo "#!/bin/sh" > /etc/service/node/run
        - echo "npm run start --prefix ${TUGBOAT_ROOT}/styleguide" >> /etc/service/node/run
        - chmod +x /etc/service/node/run

    # Collection of urls to compare visual results.
    visualdiffs:
      - /
      - /component/composite-card/
      - /component/composite-hero/
      - /component/composite-main-navigation/
      - /component/composite-secondary-navigation/
      - /component/composite-signup-form/
      - /component/identity-brand-bar/
      - /component/identity-global-footer/
      - /component/identity-local-footer/
      - /component/identity-lockup/
      - /component/identity-logo/
      - /component/identity-masthead/
      - /component/simple-alert/
      - /component/simple-button/
      - /component/simple-cta/
      - /component/simple-date-stacked/
      - /component/simple-link/
      - /component/simple-media/
      - /component/simple-nav-toggle/
      - /component/simple-quote/
      - /component/simple-site-search/
      - /component/simple-skiplinks/
